# Generated by Django 4.2 on 2026-02-20 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsession',
            name='meeting_id',
        ),
        migrations.AlterField(
            model_name='classsession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='meeting_room',
            field=models.CharField(default='TBD', max_length=255),
        ),
    ]
