# Generated by Django 4.2 on 2026-03-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_attendance_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='join_time',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='leave_time',
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]