# Generated by Django 4.2 on 2026-02-11 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_studentprofile_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.classsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.studentprofile')),
            ],
        ),
    ]
