# Generated by Django 4.2 on 2026-03-16 17:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_join_leave_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='join_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='courses.classsession'),
        ),
    ]
