# Generated by Django 4.2 on 2026-02-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
