# Generated by Django 4.2 on 2026-03-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_attendance_join_time_alter_attendance_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='join_time',
            field=models.DateTimeField(),
        ),
    ]
