# Generated by Django 4.2 on 2026-02-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_classsession_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='meeting_room',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
